/* Generated By:JavaCC: Do not edit this line. CalculatorParserConstants.java */
package com.larissa.android.calculator;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CalculatorParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EQUALS = 2;
  /** RegularExpression Id. */
  int MULTIPLY = 3;
  /** RegularExpression Id. */
  int DIVIDE = 4;
  /** RegularExpression Id. */
  int ADD = 5;
  /** RegularExpression Id. */
  int SUBTRACT = 6;
  /** RegularExpression Id. */
  int POWER = 7;
  /** RegularExpression Id. */
  int LPAREN = 8;
  /** RegularExpression Id. */
  int RPAREN = 9;
  /** RegularExpression Id. */
  int PI = 10;
  /** RegularExpression Id. */
  int E = 11;
  /** RegularExpression Id. */
  int NUMBER = 12;
  /** RegularExpression Id. */
  int DIGITS = 13;
  /** RegularExpression Id. */
  int NUM = 14;
  /** RegularExpression Id. */
  int SIN = 15;
  /** RegularExpression Id. */
  int COS = 16;
  /** RegularExpression Id. */
  int TAN = 17;
  /** RegularExpression Id. */
  int SQRT = 18;
  /** RegularExpression Id. */
  int FACTORIAL = 19;
  /** RegularExpression Id. */
  int LOG = 20;
  /** RegularExpression Id. */
  int LN = 21;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"=\"",
    "\"*\"",
    "\"/\"",
    "\"+\"",
    "\"-\"",
    "\"^\"",
    "\"(\"",
    "\")\"",
    "\"pi\"",
    "\"e\"",
    "<NUMBER>",
    "<DIGITS>",
    "<NUM>",
    "\"sin\"",
    "\"cos\"",
    "\"tan\"",
    "\"sqrt\"",
    "\"!\"",
    "\"log\"",
    "\"ln\"",
  };

}
